package co.com.soaint.finanmovilsa.interfaz;

import co.com.soaint.finanmovilsa.modelo.bo.Credito;

/**
 * This class was automatically generated by the data modeler tool.
 */

public interface IServiceCredito {

    public Integer calcularCredito(Credito credito);

}