package co.com.soaint.finanmovilsa.modelo.dto;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class ApiFecha{

	String currentDateTime;
	
	public String getCurrentDateTime() {
		return currentDateTime;
	}

	public void setCurrentDateTime(String currentDateTime) {
		this.currentDateTime = currentDateTime;
	}

	public ApiFecha() {
	}

}