package co.com.soaint.finanmovilsa.modelo.bo;

import java.io.Serializable;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Credito implements Serializable{

	private static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("Descripción solicitud de credito")
	private java.lang.String descripcionCredito;
	@org.kie.api.definition.type.Label("Valor del credito")
	private Integer valorCredito;
	@org.kie.api.definition.type.Label("Amortización (meses)")
	private java.lang.Integer amortizacion;
	@org.kie.api.definition.type.Label("Salario")
	private Integer salarioPersona;
	@org.kie.api.definition.type.Label("Gastos mensuales")
	private Integer gastosPersonaMes;

	private java.lang.Boolean estadoCredito;
	private java.lang.String razon;

	public Credito() {
	}

	public java.lang.String getDescripcionCredito() {
		return this.descripcionCredito;
	}

	public void setDescripcionCredito(java.lang.String descripcionCredito) {
		this.descripcionCredito = descripcionCredito;
	}

	public java.lang.Integer getAmortizacion() {
		return this.amortizacion;
	}

	public void setAmortizacion(java.lang.Integer amortizacion) {
		this.amortizacion = amortizacion;
	}

	public java.lang.Integer getValorCredito() {
		return this.valorCredito;
	}

	public void setValorCredito(java.lang.Integer valorCredito) {
		this.valorCredito = valorCredito;
	}

	public java.lang.Integer getSalarioPersona() {
		return this.salarioPersona;
	}

	public void setSalarioPersona(java.lang.Integer salarioPersona) {
		this.salarioPersona = salarioPersona;
	}

	public java.lang.Integer getGastosPersonaMes() {
		return this.gastosPersonaMes;
	}

	public void setGastosPersonaMes(java.lang.Integer gastosPersonaMes) {
		this.gastosPersonaMes = gastosPersonaMes;
	}

	public java.lang.Boolean getEstadoCredito() {
		return this.estadoCredito;
	}

	public void setEstadoCredito(java.lang.Boolean estadoCredito) {
		this.estadoCredito = estadoCredito;
	}

	public java.lang.String getRazon() {
		return this.razon;
	}

	public void setRazon(java.lang.String razon) {
		this.razon = razon;
	}

	public Credito(java.lang.String descripcionCredito,
			java.lang.Integer valorCredito, java.lang.Integer amortizacion,
			java.lang.Integer salarioPersona,
			java.lang.Integer gastosPersonaMes,
			java.lang.Boolean estadoCredito, java.lang.String razon) {
		this.descripcionCredito = descripcionCredito;
		this.valorCredito = valorCredito;
		this.amortizacion = amortizacion;
		this.salarioPersona = salarioPersona;
		this.gastosPersonaMes = gastosPersonaMes;
		this.estadoCredito = estadoCredito;
		this.razon = razon;
	}

}