package co.com.soaint.finanmovilsa.modelo.bo;

import java.io.Serializable;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Persona implements Serializable{

	private static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "Primer nombre")
	private java.lang.String primerNombre;
	@org.kie.api.definition.type.Label(value = "Segundo nombre")
	private java.lang.String segundoNombre;
	@org.kie.api.definition.type.Label(value = "Primer apellido")
	private java.lang.String primerApellido;
	@org.kie.api.definition.type.Label(value = "Segundo apellido")
	private java.lang.String segundoApellido;
	@org.kie.api.definition.type.Label(value = "Tipo de documento")
	private java.lang.String tipoDocumento;
	@org.kie.api.definition.type.Label(value = "Número de documento")
	private java.lang.String numeroDocumento;
	@org.kie.api.definition.type.Label(value = "Fecha de nacimiento")
	private java.util.Date fechaNacimiento;

	public Persona() {
	}

	public java.lang.String getPrimerNombre() {
		return this.primerNombre;
	}

	public void setPrimerNombre(java.lang.String primerNombre) {
		this.primerNombre = primerNombre;
	}

	public java.lang.String getSegundoNombre() {
		return this.segundoNombre;
	}

	public void setSegundoNombre(java.lang.String segundoNombre) {
		this.segundoNombre = segundoNombre;
	}

	public java.lang.String getPrimerApellido() {
		return this.primerApellido;
	}

	public void setPrimerApellido(java.lang.String primerApellido) {
		this.primerApellido = primerApellido;
	}

	public java.lang.String getSegundoApellido() {
		return this.segundoApellido;
	}

	public void setSegundoApellido(java.lang.String segundoApellido) {
		this.segundoApellido = segundoApellido;
	}

	public java.lang.String getTipoDocumento() {
		return this.tipoDocumento;
	}

	public void setTipoDocumento(java.lang.String tipoDocumento) {
		this.tipoDocumento = tipoDocumento;
	}

	public java.lang.String getNumeroDocumento() {
		return this.numeroDocumento;
	}

	public void setNumeroDocumento(java.lang.String numeroDocumento) {
		this.numeroDocumento = numeroDocumento;
	}

	public java.util.Date getFechaNacimiento() {
		return this.fechaNacimiento;
	}

	public void setFechaNacimiento(java.util.Date fechaNacimiento) {
		this.fechaNacimiento = fechaNacimiento;
	}

	public Persona(java.lang.String primerNombre,
			java.lang.String segundoNombre, java.lang.String primerApellido,
			java.lang.String segundoApellido, java.lang.String tipoDocumento,
			java.lang.String numeroDocumento, java.util.Date fechaNacimiento) {
		this.primerNombre = primerNombre;
		this.segundoNombre = segundoNombre;
		this.primerApellido = primerApellido;
		this.segundoApellido = segundoApellido;
		this.tipoDocumento = tipoDocumento;
		this.numeroDocumento = numeroDocumento;
		this.fechaNacimiento = fechaNacimiento;
	}

}